name: arena_connect
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations: 
        sdk: flutter
    cached_network_image: ^3.3.0
    flutter_svg: ^2.0.9
    google_fonts: ^6.2.1
    icons_plus: ^5.0.0
    shared_preferences: ^2.3.3
    image_cropper: ^8.0.2
    image_picker: ^1.1.2
    image: ^4.3.0
    device_preview: ^1.2.0
    decimal: ^3.0.2
    calendar_date_picker2: ^1.1.7
    http: ^1.2.2
    dotted_line: ^3.2.3
    intl: ^0.19.0
    screenshot: ^3.0.0
    path_provider: ^2.1.5
    share_plus: ^10.1.3
    carousel_slider: ^5.0.0
    url_launcher: ^6.3.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
        - images/
        - images/background-image.png
        - images/arena-connect1.png

    fonts:
        - family: Kanit
          fonts:
              - asset: fonts/Kanit-Regular.ttf
        - family: SourceSans3
          fonts:
              - asset: fonts/SourceSans3-Regular.ttf
        - family: Poppins
          fonts: 
            - asset: fonts/PoppinsBold.ttf
              weight: 700
            - asset: fonts/PoppinsRegular.ttf
              weight: 400
            - asset: fonts/PoppinsMedium.ttf
              weight: 500
            - asset: fonts/PoppinsLight.ttf
              weight: 300
